import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import {
  products, hotels, restaurants, itineraries, events,
  freelanceGigs, communityPosts, tours, reviewsTable
} from "@shared/schema";

async function seed() {
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool);

  console.log("Seeding database...");

  await db.insert(products).values([
    { name: "Angkor Wat Art Print (Canvas)", category: "Art & Souvenirs", price: 45, image: "🖼️", rating: 4.8, sales: 342, supplier: "Heritage Artisans Co.", commission: 25, description: "Beautiful hand-painted canvas print of the iconic Angkor Wat temple." },
    { name: "Cambodian Silk Scarf (Premium)", category: "Fashion", price: 89, image: "🧣", rating: 4.9, sales: 215, supplier: "Silk Roads Collective", commission: 20, description: "Premium handwoven Cambodian silk scarf in traditional patterns." },
    { name: "Temple Guidebook (Digital + Print)", category: "Digital Products", price: 29, image: "📚", rating: 4.7, sales: 1240, supplier: "OnlineGuide Media", commission: 40, description: "Comprehensive guide to Cambodia's temples with maps and history." },
    { name: "Khmer Cooking Spice Kit", category: "Food & Beverages", price: 34, image: "🌶️", rating: 4.6, sales: 428, supplier: "Spice Route Exports", commission: 22, description: "Authentic Khmer cooking spice kit with 12 traditional spices." },
    { name: "Bamboo Eco-Backpack", category: "Travel Gear", price: 76, image: "🎒", rating: 4.9, sales: 567, supplier: "EcoTravel Innovations", commission: 18, description: "Sustainable bamboo fiber backpack, perfect for eco-conscious travelers." },
    { name: "AI Guide Voice Tour (Lifetime)", category: "Digital Products", price: 149, image: "🤖", rating: 4.8, sales: 892, supplier: "OnlineGuide AI Labs", commission: 35, description: "Lifetime access to AI-powered voice tour guide for all SE Asia destinations." },
    { name: "Handwoven Krama Scarf", category: "Fashion", price: 25, image: "🧶", rating: 4.5, sales: 780, supplier: "Rural Artisans Network", commission: 30, description: "Traditional Cambodian krama scarf handwoven by rural artisans." },
    { name: "Kampot Pepper Collection", category: "Food & Beverages", price: 42, image: "🫚", rating: 4.9, sales: 365, supplier: "Kampot Pepper Co.", commission: 25, description: "World-famous Kampot pepper in three varieties: black, red, and white." },
  ]).onConflictDoNothing();

  await db.insert(hotels).values([
    { name: "Raffles Hotel Le Royal", location: "Phnom Penh, Cambodia", rating: 4.9, reviews: 1284, price: 350, image: "🏨", amenities: ["Pool", "Spa", "Restaurant", "Bar", "Wifi", "Room Service"], type: "Luxury", ecoCertified: true, description: "Historic luxury hotel in the heart of Phnom Penh." },
    { name: "Shinta Mani Angkor", location: "Siem Reap, Cambodia", rating: 4.8, reviews: 956, price: 220, image: "🌴", amenities: ["Pool", "Spa", "Restaurant", "Wifi", "Airport Shuttle"], type: "Boutique", ecoCertified: true, description: "Award-winning boutique hotel near Angkor temples." },
    { name: "Six Senses Krabey Island", location: "Koh Krabey, Cambodia", rating: 4.9, reviews: 412, price: 850, image: "🏝️", amenities: ["Private Pool", "Spa", "Beachfront", "Restaurant", "Water Sports"], type: "Resort", ecoCertified: true, description: "Private island resort with stunning ocean views." },
    { name: "Rosewood Phnom Penh", location: "Phnom Penh, Cambodia", rating: 4.7, reviews: 823, price: 280, image: "🏙️", amenities: ["Skybar", "Spa", "Restaurant", "Gym", "Wifi"], type: "Luxury", ecoCertified: false, description: "Modern luxury hotel with panoramic city views." },
    { name: "Jaya House River Park", location: "Siem Reap, Cambodia", rating: 4.8, reviews: 645, price: 180, image: "🌿", amenities: ["Pool", "Restaurant", "Spa", "Garden", "Bikes"], type: "Boutique", ecoCertified: true, description: "Riverfront boutique hotel with lush tropical gardens." },
    { name: "The Balé Phnom Penh", location: "Phnom Penh, Cambodia", rating: 4.6, reviews: 387, price: 150, image: "🏢", amenities: ["Pool", "Gym", "Restaurant", "Wifi", "Laundry"], type: "Standard", ecoCertified: false, description: "Modern hotel with comfortable rooms and great amenities." },
  ]).onConflictDoNothing();

  await db.insert(restaurants).values([
    { name: "Malis Restaurant", cuisine: "Fine Khmer Dining", location: "Phnom Penh", rating: 4.8, reviews: 1240, priceRange: "$$$", image: "🥘", features: ["Loyalty Rewards", "Table Booking", "POS Integrated"], description: "Award-winning Khmer fine dining by celebrity chef Luu Meng." },
    { name: "Cuisine Wat Damnak", cuisine: "Authentic Cambodian", location: "Siem Reap", rating: 4.9, reviews: 856, priceRange: "$$$", image: "🍲", features: ["Loyalty Rewards", "Table Booking"], description: "Innovative Cambodian cuisine using local ingredients." },
    { name: "The Sugar Palm", cuisine: "Contemporary Khmer", location: "Siem Reap", rating: 4.7, reviews: 512, priceRange: "$$", image: "🍛", features: ["Table Booking", "POS Integrated"], description: "Traditional Cambodian recipes with a modern twist." },
    { name: "Khema La Poste", cuisine: "French & Cambodian", location: "Phnom Penh", rating: 4.6, reviews: 923, priceRange: "$$$", image: "🍷", features: ["Loyalty Rewards", "POS Integrated"], description: "French-Cambodian fusion in a colonial-era building." },
    { name: "Romdeng", cuisine: "Cambodian Street Food", location: "Phnom Penh", rating: 4.5, reviews: 678, priceRange: "$$", image: "🍜", features: ["Table Booking"], description: "Social enterprise restaurant serving traditional Cambodian street food." },
    { name: "Haven Training Restaurant", cuisine: "International", location: "Siem Reap", rating: 4.7, reviews: 445, priceRange: "$$", image: "🍽️", features: ["Table Booking", "Loyalty Rewards"], description: "Training restaurant supporting underprivileged youth." },
  ]).onConflictDoNothing();

  await db.insert(itineraries).values([
    { title: "Angkor Temples 3-Day Immersion", duration: "3 days", difficulty: "Moderate", price: 299, rating: 4.9, aiGuided: true, languages: ["English", "Khmer", "French"], sites: [{ name: "Angkor Wat", description: "The world's largest religious monument", duration: "3 hours" }, { name: "Bayon Temple", description: "Famous for its giant stone faces", duration: "2.5 hours" }, { name: "Ta Prohm", description: "The 'Tomb Raider' temple with jungle ruins", duration: "2 hours" }], description: "Immerse yourself in the ancient Angkor civilization." },
    { title: "Phnom Penh Cultural Deep Dive", duration: "2 days", difficulty: "Easy", price: 199, rating: 4.7, aiGuided: true, languages: ["English", "Khmer", "Chinese"], sites: [{ name: "Royal Palace", description: "Seat of the Cambodian monarchy", duration: "2 hours" }, { name: "Silver Pagoda", description: "Sacred temple with rare treasures", duration: "1.5 hours" }, { name: "S-21 Memorial", description: "Historical museum & reflection site", duration: "2 hours" }], description: "Discover the rich culture and history of Cambodia's capital." },
    { title: "Eco-Tourism & Countryside Adventure", duration: "4 days", difficulty: "Challenging", price: 449, rating: 4.8, aiGuided: true, languages: ["English", "Khmer"], sites: [{ name: "Tonle Sap Lake", description: "Southeast Asia's largest freshwater lake", duration: "4 hours" }, { name: "Floating Villages", description: "Traditional island communities", duration: "3 hours" }, { name: "Cardamom Mountains", description: "Pristine jungle & wildlife sanctuary", duration: "Full day" }], description: "Experience Cambodia's incredible natural beauty." },
    { title: "Food & Culture Weekend", duration: "2 days", difficulty: "Easy", price: 179, rating: 4.8, aiGuided: true, languages: ["English", "Khmer", "Japanese"], sites: [{ name: "Central Market", description: "Vibrant local food scene", duration: "2 hours" }, { name: "Cooking Class", description: "Learn traditional Khmer cuisine", duration: "3 hours" }, { name: "Night Market Tour", description: "Street food & local experiences", duration: "2.5 hours" }], description: "Taste your way through Cambodia's culinary traditions." },
  ]).onConflictDoNothing();

  await db.insert(events).values([
    { title: "AI & Global Tourism Summit 2026", date: "Nov 12-14, 2026", type: "In-Person", category: "Technology", location: "Phnom Penh, Cambodia", attendees: 0, maxAttendees: 2500, description: "The premier gathering for innovators at the intersection of AI and travel.", featured: true },
    { title: "E-Commerce Automation Mastery", date: "Aug 24, 2026", type: "Webinar", category: "E-commerce", attendees: 0, maxAttendees: 500, description: "Master the latest e-commerce automation strategies.", featured: false },
    { title: "Fintech Integration for Hospitality", date: "Sep 10, 2026", type: "Hybrid", category: "Finance", location: "Siem Reap, Cambodia", attendees: 0, maxAttendees: 300, description: "Explore fintech solutions for the hospitality industry.", featured: false },
    { title: "Sustainable Tourism Data Analytics", date: "Oct 05, 2026", type: "Virtual Workshop", category: "Technology", attendees: 0, maxAttendees: 200, description: "Learn to leverage data for sustainable tourism.", featured: false },
    { title: "Logistics Optimization Summit", date: "Dec 02, 2026", type: "In-Person", category: "Logistics", location: "Bangkok, Thailand", attendees: 0, maxAttendees: 1000, description: "Global summit on logistics and supply chain optimization.", featured: false },
  ]).onConflictDoNothing();

  await db.insert(freelanceGigs).values([
    { title: "React Developer for Booking Dashboard", client: "TravelOS Inc.", type: "Fixed Price", budget: "$1,500 - $2,500", duration: "1 month", tags: ["React", "TypeScript", "Tailwind"], proposals: 12, description: "Build a modern booking dashboard with real-time availability." },
    { title: "UI/UX Designer for Mobile App Redesign", client: "Angkor Explorers", type: "Hourly", budget: "$45 - $65/hr", duration: "3-6 months", tags: ["Figma", "Mobile UI", "Prototyping"], proposals: 34, description: "Redesign the mobile app for a leading tourism company." },
    { title: "Content Writer for Eco-Tourism Blog", client: "Green Cambodia", type: "Fixed Price", budget: "$500", duration: "2 weeks", tags: ["Copywriting", "SEO", "Travel"], proposals: 8, description: "Write engaging blog content about sustainable tourism." },
    { title: "Blockchain Smart Contract Developer", client: "CamboFinance", type: "Fixed Price", budget: "$3,000 - $5,000", duration: "2 months", tags: ["Solidity", "DeFi", "Web3"], proposals: 5, description: "Develop smart contracts for a new DeFi protocol." },
    { title: "Video Editor for Tourism Campaign", client: "Visit Cambodia", type: "Hourly", budget: "$30 - $50/hr", duration: "1 month", tags: ["Premiere Pro", "After Effects", "Motion Graphics"], proposals: 19, description: "Edit promotional videos for national tourism campaign." },
  ]).onConflictDoNothing();

  await db.insert(communityPosts).values([
    { authorName: "Sarah J.", authorRole: "Tourism Operator", authorAvatar: "👩‍💼", title: "How we increased bookings by 40% using the RDTB predictive model", content: "Wanted to share some insights from our recent campaign targeting the Angkor Wat circuit based on the AI forecasting tool. The results were incredible!", likes: 124, comments: 32, tags: ["Growth", "Case Study", "RDTB"] },
    { authorName: "David Chen", authorRole: "Tech Lead", authorAvatar: "👨‍💻", title: "Building custom integrations with the Marketplace API", content: "I've just published a new mini-course on how to connect your existing inventory system to the OnlineGuide Marketplace. Check it out!", likes: 89, comments: 14, tags: ["Development", "API", "Tutorial"] },
    { authorName: "Maria Santos", authorRole: "Content Creator", authorAvatar: "🎨", title: "My journey from freelancer to agency owner using OnlineGuide tools", content: "Started as a solo freelancer two years ago. Now I run a 12-person agency thanks to the platform's creator tools and community support.", likes: 256, comments: 47, tags: ["Success Story", "Creator Economy"] },
    { authorName: "Vuthy Khun", authorRole: "Hotel Manager", authorAvatar: "🏨", title: "Tips for maximizing your hotel's visibility on the platform", content: "After 6 months of optimizing our listing, here are the top strategies that helped us rank higher and get more bookings.", likes: 178, comments: 23, tags: ["Hospitality", "Tips", "Growth"] },
  ]).onConflictDoNothing();

  await db.insert(tours).values([
    { name: "Angkor Wat Sunrise Tour", category: "temples", location: "Siem Reap, Cambodia", price: 45, rating: 4.9, reviews: 2847, duration: "5 hours", badge: "Best Seller", image: "🌅", description: "Watch the sun rise over the world's largest religious monument with an expert guide.", features: ["Sunrise viewing", "Expert guide", "Temple pass included", "Hotel pickup"], lat: 13.4125, lng: 103.8670, maxGuests: 15, languages: ["English", "Khmer", "French", "Chinese"], guideName: "Sokha Meas" },
    { name: "Phnom Penh Street Food Adventure", category: "food", location: "Phnom Penh, Cambodia", price: 35, rating: 4.8, reviews: 1523, duration: "4 hours", badge: "Top Rated", image: "🍜", description: "Taste authentic Cambodian street food across 8 stops in the capital city.", features: ["8 food stops", "Local guide", "Drinks included", "Vegetarian options"], lat: 11.5564, lng: 104.9282, maxGuests: 12, languages: ["English", "Khmer"], guideName: "Dara Kim" },
    { name: "Tonle Sap Floating Village Cruise", category: "nature", location: "Siem Reap, Cambodia", price: 55, rating: 4.7, reviews: 983, duration: "6 hours", badge: "Eco Certified", image: "🚤", description: "Explore Southeast Asia's largest freshwater lake and its unique floating communities.", features: ["Boat cruise", "Village visit", "Bird watching", "Lunch included"], lat: 12.8333, lng: 104.0833, maxGuests: 20, languages: ["English", "Khmer", "Japanese"], guideName: "Vuthy Chea" },
    { name: "Kampot Pepper Plantation & Cave Tour", category: "adventure", location: "Kampot, Cambodia", price: 65, rating: 4.8, reviews: 672, duration: "Full day", badge: "Hidden Gem", image: "🌿", description: "Visit world-famous pepper plantations and explore mysterious limestone caves.", features: ["Pepper tasting", "Cave exploration", "River cruise", "Lunch included"], lat: 10.5940, lng: 104.1640, maxGuests: 10, languages: ["English", "Khmer", "French"], guideName: "Mony Soth" },
    { name: "Sihanoukville Island Hopping", category: "beach", location: "Sihanoukville, Cambodia", price: 89, rating: 4.6, reviews: 1245, duration: "Full day", badge: "Popular", image: "🏖️", description: "Visit 3 pristine islands with crystal-clear waters and white sand beaches.", features: ["3 islands", "Snorkeling gear", "BBQ lunch", "Boat transfers"], lat: 10.6267, lng: 103.5225, maxGuests: 25, languages: ["English", "Khmer", "Russian"], guideName: "Piseth Heng" },
    { name: "Battambang Bamboo Train & Temples", category: "culture", location: "Battambang, Cambodia", price: 42, rating: 4.7, reviews: 856, duration: "7 hours", badge: "Unique", image: "🚂", description: "Ride the famous bamboo train and explore ancient hilltop temples.", features: ["Bamboo train ride", "Temple visits", "Local market", "Guide included"], lat: 13.1023, lng: 103.1986, maxGuests: 12, languages: ["English", "Khmer"], guideName: "Chantha Ly" },
    { name: "Koh Rong Samloem Diving Experience", category: "adventure", location: "Koh Rong Samloem, Cambodia", price: 120, rating: 4.9, reviews: 438, duration: "Full day", image: "🤿", description: "Discover vibrant coral reefs and marine life around Cambodia's most beautiful island.", features: ["2 dive sites", "Equipment included", "PADI certified", "Lunch on beach"], lat: 10.5780, lng: 103.3320, maxGuests: 8, languages: ["English", "Khmer"], guideName: "Reach Sok" },
    { name: "Phnom Kulen National Park Trek", category: "nature", location: "Siem Reap, Cambodia", price: 75, rating: 4.7, reviews: 567, duration: "Full day", badge: "Adventure", image: "🏔️", description: "Trek through sacred mountains, swim under waterfalls, and see the River of 1000 Lingas.", features: ["Waterfall swim", "Sacred sites", "Jungle trek", "Picnic lunch"], lat: 13.5000, lng: 104.0000, maxGuests: 15, languages: ["English", "Khmer", "French"], guideName: "Sopheap Tep" },
    { name: "Cambodian Cooking Masterclass", category: "food", location: "Siem Reap, Cambodia", price: 38, rating: 4.9, reviews: 1891, duration: "4 hours", badge: "Top Experience", image: "👨‍🍳", description: "Learn to cook 5 authentic Khmer dishes with a professional chef at a riverside kitchen.", features: ["5 dishes", "Market tour", "Recipe booklet", "Eat your creations"], lat: 13.3622, lng: 103.8597, maxGuests: 10, languages: ["English", "Khmer", "Chinese", "Japanese"], guideName: "Chef Lyna" },
    { name: "Preah Vihear Temple Expedition", category: "temples", location: "Preah Vihear, Cambodia", price: 95, rating: 4.8, reviews: 345, duration: "Full day", badge: "UNESCO", image: "⛩️", description: "Visit the spectacular cliff-top UNESCO World Heritage temple on the Thai border.", features: ["4WD transport", "Expert historian guide", "Mountain views", "Lunch included"], lat: 14.3922, lng: 104.6797, maxGuests: 8, languages: ["English", "Khmer"], guideName: "Dr. Keo Vann" },
    { name: "Mekong River Sunset Cruise", category: "nature", location: "Phnom Penh, Cambodia", price: 28, rating: 4.6, reviews: 2156, duration: "2 hours", badge: "Value Pick", image: "🌇", description: "Cruise the mighty Mekong at golden hour with drinks and traditional music.", features: ["Welcome drink", "Live music", "Sunset views", "Photo opportunities"], lat: 11.5750, lng: 104.9170, maxGuests: 30, languages: ["English", "Khmer", "French", "Chinese"], guideName: "Captain Rith" },
    { name: "Mondulkiri Elephant Sanctuary", category: "nature", location: "Mondulkiri, Cambodia", price: 110, rating: 4.9, reviews: 789, duration: "2 days", badge: "Eco Award", image: "🐘", description: "Walk alongside rescued elephants in their natural jungle habitat — ethical, no riding.", features: ["2-day trek", "Elephant feeding", "Jungle camp", "Indigenous community visit"], lat: 12.4500, lng: 107.1880, maxGuests: 8, languages: ["English", "Khmer"], guideName: "Bunthoeun Chum" },
  ]).onConflictDoNothing();

  await db.insert(reviewsTable).values([
    { entityType: "tour", entityId: 1, authorName: "James W.", authorAvatar: "🇬🇧", rating: 5, title: "Absolutely breathtaking sunrise!", content: "Sokha was an incredible guide. The sunrise over Angkor Wat was a once-in-a-lifetime experience. Highly recommend getting there early!", helpful: 47, verified: true },
    { entityType: "tour", entityId: 1, authorName: "Yuki T.", authorAvatar: "🇯🇵", rating: 5, title: "Best tour in Cambodia", content: "Perfect organization, knowledgeable guide, and the temple pass being included made everything seamless.", helpful: 32, verified: true },
    { entityType: "tour", entityId: 2, authorName: "Sophie L.", authorAvatar: "🇫🇷", rating: 5, title: "Food paradise!", content: "We tried things we never would have found on our own. The amok and num banh chok were incredible.", helpful: 28, verified: true },
    { entityType: "tour", entityId: 3, authorName: "Mike R.", authorAvatar: "🇺🇸", rating: 4, title: "Unique floating village experience", content: "Fascinating to see how people live on the water. The bird sanctuary was a bonus. Bring sunscreen!", helpful: 15, verified: true },
    { entityType: "hotel", entityId: 1, authorName: "Catherine D.", authorAvatar: "🇦🇺", rating: 5, title: "Historic elegance at its finest", content: "The Raffles lives up to its legendary reputation. Impeccable service, stunning pool, and the best gin & tonic in Phnom Penh.", helpful: 23, verified: true },
    { entityType: "hotel", entityId: 2, authorName: "Alex K.", authorAvatar: "🇩🇪", rating: 5, title: "Perfect base for temple exploration", content: "Shinta Mani is a gem. The social enterprise aspect makes you feel good about your stay.", helpful: 19, verified: true },
    { entityType: "restaurant", entityId: 1, authorName: "Tom H.", authorAvatar: "🇨🇦", rating: 5, title: "Culinary masterpiece", content: "Chef Luu Meng's dishes are works of art. The tasting menu was the highlight of our trip to Phnom Penh.", helpful: 34, verified: true },
    { entityType: "restaurant", entityId: 2, authorName: "Maria G.", authorAvatar: "🇪🇸", rating: 5, title: "Best meal in Southeast Asia", content: "Cuisine Wat Damnak deserves every accolade. The set menu changes daily and surprises every time.", helpful: 41, verified: true },
    { entityType: "tour", entityId: 9, authorName: "Chen W.", authorAvatar: "🇨🇳", rating: 5, title: "Learned so much about Khmer cooking", content: "Chef Lyna is a wonderful teacher. The market tour was eye-opening and we actually made delicious food!", helpful: 22, verified: true },
    { entityType: "tour", entityId: 12, authorName: "Sarah B.", authorAvatar: "🇳🇿", rating: 5, title: "Life-changing elephant experience", content: "Walking with elephants in the jungle was magical. The sanctuary does incredible conservation work.", helpful: 56, verified: true },
  ]).onConflictDoNothing();

  console.log("Seeding complete!");
  await pool.end();
}

seed().catch(console.error);
